# Generated by Django 5.0.3 on 2024-04-10 11:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacenes',
            fields=[
                ('id_almacen', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('dni', models.CharField(max_length=9, unique=True)),
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=65)),
                ('mail', models.EmailField(max_length=254)),
                ('comunidad', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Directores',
            fields=[
                ('dni', models.CharField(max_length=9, unique=True)),
                ('id_Director', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=65)),
                ('mail', models.EmailField(max_length=40)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidores',
            fields=[
                ('id_Distribuidor', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, unique=True)),
                ('id_Producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('precioVenta', models.IntegerField()),
                ('precioCompra', models.IntegerField()),
                ('seccion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supermercados',
            fields=[
                ('id_Supermercado', models.IntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('comunidad', models.CharField(max_length=20)),
                ('provincia', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Encargados',
            fields=[
                ('dni', models.CharField(max_length=9, unique=True)),
                ('id_Encargado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=65)),
                ('mail', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=9)),
                ('seccion', models.CharField(max_length=20)),
                ('id_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.directores')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, unique=True)),
                ('cod_Pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaPedido', models.DateField(verbose_name=datetime.datetime(2024, 4, 10, 11, 20, 34, 403493, tzinfo=datetime.timezone.utc))),
                ('fechaEntrega', models.DateField()),
                ('entregado', models.BooleanField(default=False)),
                ('id_Cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, unique=True)),
                ('id_Producto', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
                ('id_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.almacenes')),
                ('id_distribuidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.distribuidores')),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, unique=True)),
                ('cod_Producto', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('precio_Total', models.IntegerField()),
                ('cod_Pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('dni', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('id_Empleado', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=65)),
                ('mail', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('cargo', models.CharField(max_length=20)),
                ('id_Encargado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.encargados')),
                ('id_Supermercado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.supermercados')),
            ],
        ),
        migrations.AddField(
            model_name='directores',
            name='id_Supermercado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.supermercados'),
        ),
        migrations.AddField(
            model_name='almacenes',
            name='id_supermercado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.supermercados'),
        ),
    ]
