# Generated by Django 5.0.3 on 2024-04-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_almacenes_clientes_directores_distribuidores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacenes',
            name='id_supermercado',
        ),
        migrations.RemoveField(
            model_name='productos_almacen',
            name='id_almacen',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='id_Cliente',
        ),
        migrations.RemoveField(
            model_name='directores',
            name='id_Supermercado',
        ),
        migrations.RemoveField(
            model_name='encargados',
            name='id_director',
        ),
        migrations.RemoveField(
            model_name='productos_almacen',
            name='id_distribuidor',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='id_Encargado',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='id_Supermercado',
        ),
        migrations.RemoveField(
            model_name='productos_pedido',
            name='cod_Pedido',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.DeleteModel(
            name='Almacenes',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Directores',
        ),
        migrations.DeleteModel(
            name='Distribuidores',
        ),
        migrations.DeleteModel(
            name='Productos_Almacen',
        ),
        migrations.DeleteModel(
            name='Encargados',
        ),
        migrations.DeleteModel(
            name='Empleados',
        ),
        migrations.DeleteModel(
            name='Supermercados',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Productos_Pedido',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
