# Generated by Django 5.0.3 on 2024-04-10 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_remove_almacenes_id_supermercado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('codigo_postal', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_Productos', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('precioUnitario', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=65)),
                ('mail', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.ciudades')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_Pedido', models.DateField()),
                ('fecha_Entrega', models.DateField()),
                ('estado', models.CharField(max_length=15)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Supermercados',
            fields=[
                ('id_supermercado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.ciudades')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='supermercado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.supermercados'),
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id_almacen', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('supermercado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.supermercados')),
            ],
        ),
        migrations.CreateModel(
            name='Productos_almacen',
            fields=[
                ('id_Producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.productos')),
                ('nombre', models.CharField(max_length=60)),
                ('stock', models.IntegerField()),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.almacen')),
            ],
        ),
        migrations.CreateModel(
            name='Productos_pedido',
            fields=[
                ('id_producto', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.productos')),
                ('nombre', models.CharField(max_length=60)),
                ('cantidad', models.IntegerField()),
                ('precio_Total', models.FloatField()),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.pedidos')),
            ],
        ),
    ]
